### PR TITLE
Add attendancetracker

### PR DESCRIPTION
**Pull request by c0derMo**
This PR adds an attendancetracker to the bot, which is sent before every weekday, where we can mark if we're gonna attend the lectures the next day.

### CODE REVIEW

**Comment by c0derMo** [comment]
Block sorting will be implemented in `attendancetracker.ts#getBlocks`. I'd suggest sorting by starting time -> ending time -> name, lexicographically.

Getting the index of a block currently isn't really possible, except by looking at the json, not sure how to solve this another way. We'd need some way of correctly identifying blocks, for update & removal, the array index was the only thing that worked really

**Comment by Kr0nox** [comment]
The sorting order looks good to me.

For getting the index I would suggest either implementing another subcommand like `/timetable indexlist` or adding an optinal parameter to the list command for displaying the index. In the first option we would need to get an unsorted version of the blocks. For the second each block needs to be aware of its index (in this case we could also make it a UUID. This would have the advantadge that you can list the blocks once and then delete all of them without needing to get the index again). 
Personally I would favor the approche of the UUID and then just using  a static counter as the UUID or something, to keep the number as small as possible

**Comment by c0derMo** [comment]
For the record: I just ran eslint over all new files currently on this branch with the new config from dev-docs, all are clean.

As for the index, we can make some sort of compromise, an optional parameter to `/timetable list`, a boolean just indicating whether to add the list index or not. That optional parameter will also be added to `getBlocks`, which adds the array index to the attributes of the blocks returned. As that will happen before any filtering or sorting, the index is always up to date this way, and saves us from having to generate (UU)IDs for every block manually.

**Comment by Kr0nox** [comment]
For your sorting attempt I would suggest either using a method like `getPrettyTime` from the Viesualizer or forcing the correct date format when creating a block or formatting it correctly in the blocks constructer, since ATM we don't put any constraints on the entered time format

**Comment by Kr0nox** [comment]
We can do the index system like that. What i went was when we print the index and now delete, lets say the element at index 3 a new element would move into this index, right? so when we now delete what according to list is at index 4 we might delete the wrong block

**Comment by c0derMo** [comment]
Sorting: `prettyTime` returns the time in form of a discord timestamp, which is not really usable in this instance. I guess putting constrains on time at block creation is the better way to go here.

Index: That's true, upon block deletion, indexes might change, but I think as long as we're aware of that, that's workable. I'd try to avoid having to assign custom ids to all the blocks if we can.

**Comment by Kr0nox** [comment]
Yeah, I didn't mean taking pretty time exactly put with that we could also parse (most) time formats without input restrictions, but of course that also works.

Maybe we can just add a small statement like "be aware that indexes might have changed" to the successful deletion message

**Comment by c0derMo** [comment]
Added the optional index-displaying, deletion notice & constraints to the time format.

On a different note, I still believe `attendancetrackerVisuals#getDaysBlocks` is basically a duplicate of `attendancetracker#getBlocks` and the later one should be used to avoid code duplication.

**Comment by Kr0nox** [comment]
I removed the method and replaced it. 
Are there any open issues remaining?

**Comment by Kr0nox** [comment]
I would put one thing up for discussion: at the moment the time constraints require two digits at the beginning. Would it be easier for the user to also be able to enter times with a single digit in the hours place? (e.g.: 9:45)

**Comment by Kr0nox** [comment]
And there is an issue where the attendance gets included when executing `/timetable list`

**Comment by c0derMo** [comment]
Time constraints:
They have been updated, previously, times like 99:99 would also have been allowed, now, only correct times are allowed, and don't need (or allow) a leading 0.

Attendance inclusion in `/timetable list`:
I'm not 100% sure, but this might be due to the attendance leaking into the config file. Can you look at the `timetable.json` and see, if the attendance is stored in there? If yes, if you delete it from there, the latest changes should make sure that we pass copies instead of references from the config manager, therefore, leaking over shouldn't be possible anymore.

**Comment by Kr0nox** [comment]
Yes, that fixed the issue

**Review by Kr0nox — APPROVED** [review]
Looks good to me now

**Review by Kr0nox — APPROVED** [review]
lgtm

**Pull request merged**
