### PR TITLE
Recurring tasks only for university days

### PR DESCRIPTION
**Pull request by Kr0nox**
This PR adds a special kind of recurring task, that only excecutes in weeks we have lectures and not on holidays.
It does that by parsing the official university site, where the lecture dates can be found.

There is still one issue tho. Since we excecute the timeTable task on the day before lecuteres, it may not get excecuted on the first day of lectures after a break and when the day before was a holiday or may be excecuted falsly on the day before a holiday. 
I suggest we find a fix for this issue and implement it in this branch before merging the PR

### CODE REVIEW

**Comment by Kr0nox** [comment]
and I would like to raise the question whether the compareTime function in recurring task is redundant since it's only use case is checking for equality, so this could be moved to the shouldRunAtTime function

**Comment by c0derMo** [comment]
> Since we excecute the timeTable task on the day before lecuteres, it may not get excecuted on the first day of lectures after a break and when the day before was a holiday or may be excecuted falsly on the day before a holiday.

I think the simplest solution for this would be some sort of optional "check-offset" in the constructor of `UniversityRecurringTask`, alternatively we could also introduce a "run-offset"

> and I would like to raise the question whether the compareTime function in recurring task is redundant

I think the reason for that function was in case we wanted to use a better scheduler, which doesn't check for equality, but if any tasks were triggered between now and the last time the scheduler ran - however, since our current approach (checking every minute) seems to work, I think it is indeed redundant

**Review by c0derMo — APPROVED** [review]
lgtm - we could concider adding feiertagejs to the allowed packages for dependabot inside the `dependabot.yml` file

**Review by c0derMo — APPROVED** [review]
All good

**Pull request merged**
